name: dartsrc
description: A random collection of dart programs, illustrating things about dart.

version: 0.0.0

environment:
  sdk: '>=2.17.0 <3.0.0'
dev_dependencies: {test: ^1.21.4}
dependencies:
  http: ^0.13.5
  intl: ^0.18.0
  properties: ^2.1.0
